name: Deploy to Azure VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o projeto
      uses: actions/checkout@v3

    - name: Enviar arquivos via SCP
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_KEY }}
        source: "."                     # pode ajustar se quiser ignorar arquivos
        target: "/home/${{ secrets.VPS_USER }}/app"
        strip_components: 1            # remove a pasta raiz do repositório

    - name: Acessar VPS e executar comandos via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_KEY }}
        script: |
          cd /home/${{ secrets.VPS_USER }}/app
          npm install --production
          pm2 stop ecosystem.config.js || true
          pm2 start ecosystem.config.js
          pm2 save
