name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clone o projeto
      uses: actions/checkout@v3

    - name: Enviar arquivos via SSH
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_KEY }}
        source: "."
        target: "/home/${{ secrets.VPS_USER }}/app"
        port: 22

    - name: SSH e restart via PM2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_KEY }}
        port: 22
        script: |
          cd /home/${{ secrets.VPS_USER }}/app
          npm install
          pm2 stop all || true
          pm2 start ecosystem.config.js
          pm2 save
